#
# Sera - OnePage Jekyll Theme
# Configuration File
#

# Information for compile
exclude: ["Gemfile", "README.md"]

# Sass configuration
sass:
  sass_dir: _scss

# Information for deploy
baseurl: ""

# the base hostname & protocol for your site
url: "http://localhost:4000"

exclude:
 - strapi
 - _tmp_assets
 - webhook

####################################
######   Optional Features    ######
####################################
smooth-scroll: true

####################################
###########   Plugins    ###########
####################################
plugins:
  - jekyll-archives
  - jekyll-strapi-4

strapi:
  endpoint: http://localhost:8080
  collections:
    troop-leaders:
      single_request: true
      output: false
      parameters:
        populate: "*"
    sites:
      single_request: true
      output: false
      parameters:
        populate: "*"
    events:
      single_request: true
      output: true
      permalink: "/events/:slug"
      parameters:
        populate: "*"
        sort: publishedAt:desc
      layout: post.html
    fetures:
      single_request: true
      ouput: false
      parameters:
        populate: "*"
    portfolio-items:
      single_request: true
      output: false
      parameters:
        populate: "*"
    traits:
      single_request: true
      output: false
    eagles:
      single_request: true
      output: false
      parameters:
        populate: "*"

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: "archive"
  permalinks:
    category: "/category/:name/"
    tag: "/tag/:name/"

#######################################################
#######################################################
###############   HEADER INFORMATIONS   ###############
#######################################################
#######################################################

form-endpoint: https://submit-form.com/3tM8B0vvj

# This is your site title
title: Troop 27 - Manchester, Connecticut
# Website language
lang: en-US
# Header Title
header-title: A Troop With <strong>Opportunities</strong>
# Header Tagline
headter-tagline: Troop 27

####################################
######   CTA Header Buttons   ######
####################################

# Focus Buttons
header-focus-button:
  title: Join Today
  url: "#contact"

# Secondary Buttons
header-secondary-button:
  title: Discover More
  url: "#about"

#
# This is your email adress, contact from send here all emails from contact section
# IMPORTANT: you can modify contact form from this static template, but now works contact form works with a free external server
# To configure this contact form, first please send a fictive email afeter you enter below your email and verify that :)
#
email: your_email@example.com

# Offer Banner Link
# Default link is a link to all Sera OnePage products
banner-link: '#'

####################################
######  Global Social Links   ######
####################################
youtube: "#"
pinterest: "#"
facebook: "#"
twitter: "#"
google-plus: "#"
vimeo: "#"

#########################
######   Widgets   ######
#########################

#
# About Blog Author Widget
#
about-widget:
  author-avatar: avatar-02.jpg
  author-name: John Doe
  author-tagline: Blog Author
  author-info: Cum sociis que penatibus et magnis dis parturient montes lorem, nascetur ridiculus mus. Donec quam felis, ultricies.
  author-social-links:
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"

# Google Map JS api
key-api: YOUR_GOOGLE_MAP_API_KEY
map-text: Sera Google Map
map-lat: 44.4267674
map-lng: 26.102538399999958

# Enter your Mailchimp User ID and Campaign ID
# @TODO: Add in a link for where to find these
mailchimp:
  user-id: REPLACEME
  list-id: REPLACEME

####
#
# Hi you now use Sera - OnePage Jekyll Theme created by Ohkimur
#
# Below are each section from the website in order from top to bottom
# @TODO Edit each sections with your real information and each section from Sera will autocomplete with your information
#
####

#####################################
#############   About   #############
#####################################
about-title: Welcome to Troop 27
about-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl.

#####################################
#############  Features  ############
#####################################
features-title: Our Goals
features-description: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante.

#
# Features
#
features:
  # Feature
  - title: Turn our Scouts into leaders
    description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
    icon: pe-7s-vector

  # Feature
  - title: Create connections in our community
    description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
    icon: pe-7s-help2

  # Feature
  - title: Leave the world better than we found it
    description: Maecenas sed laoreet urna. Praesent eget tristique tortor. Suspendisse consequat sed turpis in mattis.
    icon: pe-7s-airplay

#####################################
############  Portfolio  ############
#####################################
portfolio-title: Troop Portfolio
portfolio-description: Maecenas tempus nec mi et placerat. Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis.

#
# Portfolio Grid
#
portfolio-categories:
  [Campouts, Eagle Projects, Meetings, Community Service, High Adventure, Merit Badges]
portfolio:
  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Graphic Design]
    image: img-01.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Graphic Design, Logo, Websites]
    image: img-02.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Graphic Design, Logo, Photography]
    image: img-03.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Video, Photography]
    image: img-04.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Development, Logo]
    image: img-05.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Development, Video]
    image: img-06.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Graphic Design]
    image: img-07.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Websites, Video]
    image: img-08.jpg
    url: "#"

  # Portfolio Item
  - title: S<span class="thin">era</span> Style
    categories: [Photography, Logo]
    image: img-09.jpg
    url: "#"

#####################################
##########  Core Features  ##########
#####################################
core-title: What Makes Troop 27 Unique
core-description: Duis at odio vitae ex gravida volutpat. Nulla finibus aliquet diam ut eleifend. Mauris consequat interdum quam. Mauris dui sapien, efficitur et cursus id, molestie fringilla turpis aliquet diam ut eleifend.

#
# Core Features Left
#
core-features-left:
  # Feature
  - name: Scout-led
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-light

  # Feature
  - name: Experience
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-drop

  # Feature
  - name: High Adventure
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-coffee

  # Feature
  - name: Community
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-smile

#
# Core Features Right
#
core-features-right:
  # Feature
  - name: Customizable
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-wine

  # Feature
  - name: Inclusive
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-monitor

  # Feature
  - name: Monthly Campouts
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-crop

  # Feature
  - name: Many Eagles
    description: Lorem ipsum dolor sit amet, consectetuer adipiscing diam.
    icon: pe-7s-camera

#####################################
########### Testimonials ############
#####################################
testimonials-title: Testimonials
testimonials-description: Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi.

#
# Testimonials
#
testimonials:
  # Client
  - name: Johnatan Doe
    url: http://themeforest.net
    url-text: ThemeForest.net
    avatar: avatar-01.jpg
    cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
    logo-img: themeforest.png

  # Client
  - name: Adam Smith
    url: http://codecanyon.net
    url-text: CodeCanyon.net
    avatar: avatar-02.jpg
    cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
    logo-img: codecanyon.png

  # Client
  - name: Irene Warner
    url: http://videohive.net
    url-text: VideoHive.net
    avatar: avatar-03.jpg
    cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
    logo-img: videohive.png

  # Client
  - name: Richard Ryan
    url: http://audiojungle.net
    url-text: AudioJungle.net
    avatar: avatar-04.jpg
    cite: Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer varius adipiscing lectus, eu ornare lectus semper in. Aenean at tincidunt sem. Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed.
    logo-img: audiojungle.png

#####################################
############# Our Blog ##############
#####################################
blog-title: Our Events
blog-description: Interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#####################################
############### Team ################
#####################################
team-title: Meet Our Troop Leaders
team-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Team Members
#
team:
  # Team Member
  - name: Jack Skilton
    tagline: Graphic Designer
    avatar: avatar-01.jpg

    # Social Links
    # youtube: "#"
    # pinterest: "#"
    # facebook: "#"
    # twitter: "#"
    # google-plus: "#"
    # vimeo: "#"

  # Team Member
  - name: James Young
    tagline: Developer
    avatar: avatar-02.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

  # Team Member
  - name: Johnatan Doe
    tagline: Hacker
    avatar: avatar-04.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

  # Team Member
  - name: Ecaterina Doe
    tagline: Support Expert
    avatar: avatar-03.jpg

    # Social Links
    youtube: "#"
    pinterest: "#"
    facebook: "#"
    twitter: "#"
    google-plus: "#"
    vimeo: "#"

#####################################
########## Pricing Tables ###########
#####################################
pricing-title: Pricing Tables
pricing-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat vitae volutpat sed, suscipit et nisi. Nulla a tellus at turpis gravida congue non sed nisl. Pellentesque scelerisque eu neque et tincidunt.

#
# Plan Personal
#
plan-personal-price: $99
plan-personal-offer-1-title: 01 PSD Pack
plan-personal-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-offer-2-title: 100 Support Tickets
plan-personal-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-personal-url: "#"

#
# Plan Business
#
plan-business-price: $499
plan-business-offer-1-title: 05 PSD Pack
plan-business-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-offer-2-title: 1000 Support Tickets
plan-business-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-business-url: "#"

#
# Plan Ultimate
#
plan-ultimate-price: $999
plan-ultimate-offer-1-title: 10 PSD Pack
plan-ultimate-offer-1-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-offer-2-title: Support Unlimited
plan-ultimate-offer-2-info: Mauris gravida fringilla est. Proin sodales sed erat et cursus. Mauris quis posuere enim.
plan-ultimate-url: "#"

#####################################
############   Contact   ############
#####################################
contact-title: Contact Us
contact-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.

#####################################
#############   Footer   ############
#####################################
footer-description: Nulla a tellus at turpis gravida congue non interdum et malesuada fames ac ante ipsum primis in faucibus. Morbi id ornare ante. Cras odio nibh, volutpat.
footer-copyright-text: Ohkimur
footer-copyright-url: https://github.com/ohkimur
footer-copyright-year: 2021
